### ISSUE TITLE
Бан пользователя dracony

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/chat#3]
Это первый раз, за историю чата, когда разумный участник (не тролль или спамер) явно и специально игнорирует правила. И в связи с неоднократными нарушениями оных со стороны пользователя @dracony - выношу на обсуждение вопрос о его перманентном бане.

Просьба оставлять "+1" или "-1" в виде смайлика к этому комменту, окончание голосования 18.09.2016.

:+1: - За
:-1: - Против. В этом случае пользователь будет разблокирован сразу же после окончания голосования.

**Comment by jhaoda** [comment]
Зачем каменты, если можно лайкнуть или дизлайкнуть псто?

**Comment by SerafimArts** [comment]
@jhaoda так я вроде так и сделал =)

**Comment by jhaoda** [comment]
@SerafimArts ну так ты просишь в каментах это писать

**Comment by SerafimArts** [comment]
@jhaoda ты давно f5 нажимал? =)

**Comment by jhaoda** [comment]
@SerafimArts а должен был нажимать?

**Comment by Malezha** [comment]
Слишком много внимание целому одному нарушителю? Кстати, если не ошибаюсь, то его уже блокировали не раз именно на спам по пикси, так какие могут быть поблажки рецидивисту?

**Comment by SerafimArts** [comment]
@Malezha как бы к нему не относились - он вполне разумный человек, который может помогать сообществу и новичкам, так что заслужил хотя бы возможность справедливого суда участников, а не "произвола модераторов" ;)

**Comment by Malezha** [comment]
@SerafimArts правила одни для всех, нет? @aios пару раз банили сразу, без суда и следствия, хотя он не просто может, а уже помогает в чате. Разумному человеку достаточно предупреждения и/или блокировки разок.
Хотя чего я пишу, 6 голосов за бан и 0 против - решение почти что принято.

**Comment by dracony** [comment]
Ну уж прям спамер. Я может раз в два месяца захожу со ссылкой. Все другое
это холивары в стиле "что лучше" и пользователи в чате сами их
поддерживают. Вот например в последний раз о Блейде спорили, и всем норм
было, пока @JhaoDa не пришел и сказа что остановитесь ибо оффтопик))

2016-09-15 13:10 GMT+02:00 Kirill Nesmeyanov <notifications@github.com>:

**Comment by Malezha** [comment]
@dracony с ним не согласились, т.к. блейд часть фреймворка. Но простите, какое отношение к ларавел имеет группа вк по пикси?

**Comment by aios** [comment]
@dracony ну ваше присутствие в чате и так некоторым личностям не приятно. так вы еще и масла в огонь подливаете. Пилите шура свою пиксю и не лезьте со своей конченной группой в которой в добавок ничерта нет даже участников.

**Comment by arsen-s** [comment]
не думаю что из за какой то ссылки стоит принимать такие жесткие меры, все мы люди

**Comment by aios** [comment]
@arsen-s я завтра приду к тебе домой и наложу прямо посреди гостинной - в добавок к твоему оторопевшему лицу я скажу "Чувак - ну добротное - бери не жалко." на что ты оторопеешь еще больше.

Дело не в ссылке - а в отношении.

**Comment by SerafimArts** [comment]
@aios просьба воздержаться от резких выражений =)

**Comment by aios** [comment]
@SerafimArts Извиняюсь - но иногда мне кажется человеку один раз сказать в лоб - чем ходить вокруг да около.

**Comment by greabock** [comment]
Думаю, что временный бан не имеет смысла, ввиду того факта, что нарушитель не является регулярным резидентом. С другой стороны, пермабан - слишком жестко. Хотя человек и мудак (это мое частное мнение), всё же излишних неудобств он не доставляет (опять же ввиду того факта, что он не регулярный обитатель). Предлагаю дождаться следующего нарушения - и тогда можно оформить перманентный бан с чистой совестью.

**Comment by dracony** [comment]
Ну ты с другой стороны посмотри ))) группа то только одна, больше постить
то нечего. А дважды я то же самое не скидываю.

**Comment by aios** [comment]
@dracony ну собственно кроме ехидной ухмылки я от вас ничего другого и не ожидал "обожаю" данный типаж людей.

 Короче надеюсь мой голос принесет пользу.

**Comment by SerafimArts** [comment]
Мнением большинства бан снят. Последнее китайское =)
