### ISSUE TITLE
Предложения по послаблению ограничений в чатиках

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/chat#4]
Начало дискуссии: https://gitter.im/LaravelRUS/offtop?at=596cbddc3230e14f3a68f0d1

## Историческая сводка

Оффтоп чатик создавался с целью простой болталки о личном и вообще обо всём на свете. Постить котиков и угорать.

## Что происходит сейчас

Приходит новичок, спрашивает про Homestead, его отправляют в оффтоп. А там треш, угар и содомия. Не всегда, конечно, но всё же.

## Предложение

Предложений было несколько, пообсуждали в целом, но решили что всё же создать отдельную голосовалку по теме. Так что предлагается ставить свои :+1: (**остальные смайлики буду игнорировать при подсчёте голосов!!!!111пыщ**) за тот вариант, который вам больше всего нравится. 

Напоминаю, что если вас устраивают несколько вариантов, то символы :+1: можно проставить нескольким вариантам =)

Все варианты представлены ниже :point_down: 

Вариантов 3.5:
1) Оставить как есть
2) Вернуть как раньше было
3) Создать отдельный чатик
4) Другие идеи? (добавлю в списочек)

Итоги подведём через недельку, думаю хватит всем времени.

**Comment by SerafimArts** [comment]
Reserved 1

**Comment by SerafimArts** [comment]
Reserved 1

**Comment by SerafimArts** [comment]
Reserved 3

**Comment by SerafimArts** [comment]
Reserved 4

**Comment by webdevium** [comment]
Может отдельный канал для детей сделать? Совсем начинающих.

**Comment by atehnix** [comment]
@webdevium уровень у всех разный. Кто решать будет, достоин ли вопрос быть задан во "взрослом" чате? :D

**Comment by SerafimArts** [comment]
@webdevium ну это уже в качестве отдельного предложения, думаю. Вдруг примем какой-нибудь новый вариант и всех всё устроит, тогда не надо будет ничего создавать нового.

**Comment by Hunternnm** [comment]
Как есть сейчас - идеально. А то если создавать dev - то сразу чатики life, girls, bsd/unix, etc

**Comment by SerafimArts** [comment]
@Hunternnm ну проблему вроде как обозначили, в оффтопе смешиваются темы, вида "почему эта функция не шарит" и "я вчера женился, поздравьте". Кажется, это не слишком хорошо, ты так не считаешь?

**Comment by aios** [comment]
Почему мы подстраиваемся под пользователя? Начинающие всегда чаще или реже пробираются через тонну говна - наш оффтоп не явлется сему достаточно массивным камнем приткновения. Нам не нужны отдельные каналы. На то есть несколько причин:
1. Критическая масса рассосется
2. В чатике нужен будет модер - потому что в отедельном тоже рамки - за ними ведь следить нужно.
4. Куча наспамленного говна когда просыпаешься сразу в нескольких чатах. А полезные решения могут проскакивать во всех.
5. Рассеянное внимание - еще больше чатов для "Почитать"

Самые внимательные уже поняли что под пунктом 3 я напишу "На*й еще один канал"

Сейчас идеально - нечего основной канал захламлять вопросами про Хоумстед докер и прочее - там такие енвайронменты подтянутся на годы обсуждения. Это мое субъективное.

**Comment by Butochnikov** [comment]
Кто есть в офф чате Laravel в Slack?
Там, например, разбили все на отдельные комнаты.
Везде есть свои + или -.
С одной стороны плохо, что по смежным вопросам отправляют в оффтоп, а с другой стороны, это чат по Laravel.
Я понимаю, что сейчас наш чат самый популярный и крупный gitter чат в рунете. Стоит ли его разделять на множество чатов? Думаю, что нет.
Возможно стоит создать только один чат по смежным dev вопросам, раз уж таких вопросов много. Тогда, это будет  чат "под крылом" laravel сообщества и не оффтопик.

**Comment by Big-Shark** [comment]
Голосую за воторой вариант, так как сейчас по факту хомстед и вью эта некая часть лары, и при установке часто человек может даже не догадываться что это совсем уж другое. Вопросы по пхп и мускулю тоже оставить в основном чате, так как лара написана на пхп и мы используем мускуль (постгрю и тд), а вот вотпросы по расту, джаве, котикам и прочему, уже обсуждать в оффтоп

**Comment by jhaoda** [comment]
@Big-Shark и по html с css тоже, да? И по pgsql, потому что я, например, юзаю его с ларавел. И по vue.js, потому что многие его юзают с ларавел, а значит и по js в целом.

**Comment by Orel2888** [comment]
2 вариант, единицам это не нравилось и из-за них сделали оффтоп, почему все должны под них подстраиваться

**Comment by VladShcherbin** [comment]
@Big-Shark @Orel2888 Если второй вариант, то в чатике появятся вопросы и по node, webpack, js, vue, react, c++, css, базам данных и т.д. 

Вы готовы к этому? 😉

**Comment by slider23** [comment]
Мне кажется, не будет ничего страшного, если будут вопросы по смежным техническим вещам в чате про laravel. Так или иначе эту будет многим полезно.

**Comment by PhpNet** [comment]
Еще б поиск был по чату хоть какой нить... Или я просто не гнашел его? :smile: 
А то вроде помнишь, бывает, что 100% обсуждали и ответ был - а найти как, хз.

**Comment by VladShcherbin** [comment]
@PhpNet там есть поиск, просто не особо удобный

<details>
 <summary>вот тут</summary>

![screen shot 2017-07-21 at 11 04 27 am](https://user-images.githubusercontent.com/6711845/28454603-8635a03e-6e04-11e7-90dd-1e8c9c7dbf0b.png)

</details>

**Comment by PhpNet** [comment]
@VladShcherbin так это ж поиск по чатам а не по содержимому чата вроде :) у меня не ищет по содержимому

**Comment by VladShcherbin** [comment]
@PhpNet и по чату ищет:

<details>
 <summary>поиск</summary>

![screen shot 2017-07-21 at 11 12 08 am](https://user-images.githubusercontent.com/6711845/28454903-9580fca4-6e05-11e7-8ed0-be0dfc01680b.png)

</details>

**Comment by symbios-zi** [comment]
Голосую за второй вариант. Думаю что смежные темы не мешают чату.

**Comment by Big-Shark** [comment]
@jhaoda А ты не помнишь, раньше так и было, да еще и котиков обсуждали. И вроде жили как-то.

**Comment by jhaoda** [comment]
@Big-Shark плохо жили.

**Comment by Orel2888** [comment]
@jhaoda отлично жили, плохо было тебе только

**Comment by jhaoda** [comment]
Минимум половина тех, кто выступает за возврат к старому укладу, бывают чате раз в пятилетку. Вам не по хер ли уже, а? Или что, вы вернётесь в чат вместе с возвратом старых традиций?

**Comment by SerafimArts** [comment]
@jhaoda теперь для котиков есть оффтоп. И да, по-мне, раньше было лучше. Лично меня бесит это разделение.

**Comment by VladShcherbin** [comment]
@Big-Shark @Orel2888 @SerafimArts ничего, ребята, скоро всё будет как раньше 😉

**Comment by aios** [comment]
@jhaoda нынешнее положение дел - устраивает только тебя и меня. остальные закидают помидорами.

**Comment by atehnix** [comment]
@aios Не только. Меня тоже, в принципе, устраивает. 
Просто я считаю, что фидбэк тоже важен, т.к. мое личное мнение может не всегда совпадать с коллективным мнением сообщества. Тем более в таких вопросах, где не может существовать объективно единственно верного решения, устраивающего всех, а решить, тем не менее, что-то надо. ;)

**Comment by SerafimArts** [comment]
# Подсчёт завершён.

Победил пункт No.2. Это значит что ничего не меняется за теми исключениями:
1) В основном чате допустимы темы смежные с ларкой:
- Laravel/Symfony (?)
- PHP
- Vue/React/Node/etc
- Docker/Vagrant/etc
- Nginx/Apache/etc
- Алгоритмы
- и проч. на ту же тему
2) По всем остальным вопросам в оффтоп (в том числе по языкам Java/C#/C++/другим).
